# Generated by Django 4.2 on 2023-05-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, unique=True, verbose_name='Название транспортной компании')),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('transport', models.CharField(max_length=100, verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Поставщики',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название продукта')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
                ('provider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modelsapp.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя покупателя')),
                ('products', models.ManyToManyField(to='modelsapp.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Покупатели',
                'verbose_name_plural': 'Покупатели',
            },
        ),
    ]
