# Generated by Django 4.2 on 2023-05-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='delivery_date',
        ),
    ]
